# Generated by Django 5.0.7 on 2024-11-09 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_comment_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', '-'), ('in_progress', '='), ('done', '+'), ('expired', '!')], default='todo', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='tasks.task')),
            ],
        ),
    ]
