# Generated by Django 5.0.7 on 2024-11-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_priority_alter_task_status_taskgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.RemoveField(
            model_name='taskgroup',
            name='tasks',
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='tasks',
            field=models.ManyToManyField(related_name='group', to='tasks.task'),
        ),
    ]
